# Get rid of the newline at the start of the prompt
add_newline = false

# Define the order of the format
format = """$username$hostname $directory$git_branch$character"""

[username]
show_always = true
style_user = "bold blue"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold blue"
format = "[@$hostname]($style) "

[directory]
style = "bold cyan"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bold magenta"
format = "on [$symbol$branch]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
