- name: sync nextcloud search index
  hosts: 192.168.1.30
  gather_facts: true
  tasks:
    - name: run the sync command
      command: sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:index
      args:
        chdir: /var/www/nextcloud
